config/routes.rb
Rails.application.routes.draw do
  devise_for :admin,skip:[:regstrations,:passwords],controllers:{
    sessions:"admin/sessions"
  }
  namespace :admin do
    root to:"homes#top"
    resources:customers,except:[:new,:create,:destroy]
    resources:items,exept:[:destroy]
    resources:genres,except:[:new,:show,:destroy]
    resources:orders,only:[:show,:update]
    resources:order_items,only:[:update]
  end

  devise_for :customers,skip:[:passwords],controllers:{
    registrations:"customer/registrations",
    sessions:"customer/sessions"
  }

  scope module: :customer do
    root to: "homes#top"
    get "/about" => "homes#about"
    resources:items,only:[:index,:show]
    resources:cart_items,only:[:index,:create,:update,:destroy]
    delete "/cart_items/" => "cart_items#destroy_all",as:"destroy_all"
    post "/orders/confirm" => "orders#confirm"
    get "/orders/complete" => "orders#complete"
    resources:orders,only:[:new,:create,:index,:show]
    resource:customers,only:[:show,:edit,:update]
    get "/customers/mypage" => "customers#show"
    get "/customers/mypage/edit" => "customers#edit"
    patch "/customers/mypage/update" => "customers#update"
    get "/customers/unsubscribe" => "customers#unsubscribe"
    patch "/customers/withdraw" => "customers#withdraw"
    resources:shippings,except:[:new,:show]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many:orders,dependent: :destroy
  has_many:cart_items,dependent: :destroy
  has_many:shippings,dependent: :destroy
  
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :email, presence: true
  validates :post_code, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  validates :encrypted_password, presence: true

  def full_address
    '〒' + post_code + ' ' + address + ' '
  end
  def full_name
    last_name + first_name
  end
  def full_name
    self.last_name + self.first_name
  end
  def full_name_kana
    self.last_name_kana + self.first_name_kana
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many:order_items,dependent: :destroy
  belongs_to:customer
  
  validates :post_code, presence: true
  validates :address, presence: true
  validates :name, presence: true

  enum payment_method:{credit_card:0,transfer:1}
  enum ordering_status:{payment_waiting:0,confirmation:1,production:2,ready_to_ship:3,shipping_finish:4}

  def sum_of_order_price
    total_price+shipping_fee
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!
  # before_action :authenticate_admin!
  def index
    @customers = Customer.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer)
    else
      redirect_to request.referer
    end
  end

  private
    def customer_params
      params.require(:customer).permit(:email, :encrypted_password, :last_name, :first_name, :last_name_kana, :first_name_kana, :post_code, :address, :phone_number, :is_quited)
    end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!
  def show
    @order = Order.find(params[:id])
    @order_items = @order.order_items
    @total_price_except_fee = @order_items.inject(0) { |sum, item| sum + item.sum_of_item_price }
    @order.total_price = @total_price_except_fee + @order.shipping_fee
  end
  
  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    if @order.confirmation?
      @order.order_items.each do |order_item|
      order_item.production_waiting!
      end
    end
    redirect_to admin_order_path(@order)
  end

  private

  def order_params
    params.require(:order).permit(:ordering_status)
  end

end

app/controllers/customer/cart_items_controller.rb
class Customer::CartItemsController < ApplicationController
  before_action :authenticate_customer!
  def index
    @cart_items = current_customer.cart_items
    @total = @cart_items.inject(0) { |sum, item| sum + item.subtotal }
  end

  def create
    @cart_item = current_customer.cart_items.new(cart_item_params)
    @cart_item.customer_id = current_customer.id
    if cart_item = current_customer.cart_items.find_by(item_id: params[:cart_item][:item_id])
      cart_item.amount += params[:cart_item][:amount].to_i
      cart_item.save
      redirect_to cart_items_path
    else
      @cart_item.save
      redirect_to cart_items_path
    end
  end

  def update
    @cart_item = CartItem.find(params[:id])
    @cart_item.update(cart_item_params)
    redirect_to cart_items_path
  end

  def destroy
    @cart_item = CartItem.find(params[:id])
    @cart_item.destroy
    redirect_to cart_items_path
  end

  def destroy_all
    @cart_items = current_customer.cart_items
    @cart_items.destroy_all
    redirect_to cart_items_path
  end

  private

  def cart_item_params
    params.require(:cart_item).permit(:item_id,:amount)
  end
end

app/controllers/customer/confirmations_controller.rb
# frozen_string_literal: true

class Customer::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customer/customers_controller.rb
class Customer::CustomersController < ApplicationController
  before_action :authenticate_customer!

  def show
    @customer=current_customer
  end

  def edit
  	@customer=current_customer
  end

  def update
  	if current_customer.update(customer_params)
  	  redirect_to customers_mypage_path
  	else
  	  redirect_to request.referer
  	end
  end

  def unsubscribe
    @customer=current_customer
  end

  def withdraw
    @customer = current_customer
    @customer.update(is_quited: true)
    reset_session
    redirect_to root_path
  end

  private
  	def customer_params
  		params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :post_code, :address, :phone_number, :email, :is_quited)
  	end
end

app/controllers/customer/homes_controller.rb
class Customer::HomesController < ApplicationController
  def top
    @items = Item.order(created_at: :desc).limit(4)
  end
  def about
  end
end

app/controllers/customer/items_controller.rb
class Customer::ItemsController < ApplicationController
  def index
    @items = Item.page(params[:page]).per(8)
    @all_items = Item.all.count
  end
  def show
    @item = Item.find(params[:id])
    @cart_item = CartItem.new
  end
end

app/controllers/customer/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customer::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < ApplicationController
  before_action :authenticate_customer!
  def new
    @order=Order.new
    @credit_card=Order.payment_methods.key(0)
    @transfer=Order.payment_methods.key(1)
    @credit_card_ja=Order.payment_methods_i18n[:credit_card]
    @transfer_ja=Order.payment_methods_i18n[:transfer]
  end

  def index
    @orders=current_customer.orders
  end

  def show
    if params[:id]=="confirm"
      redirect_to new_order_path
    else
      @order = Order.find(params[:id])
    end
  end

  def confirm
    @order=Order.new(order_params)
    @order.shipping_fee=800
    @total_price_except_fee = current_customer.cart_items.inject(0) { |sum, item| sum + item.subtotal }
    @order.total_price=@total_price_except_fee + @order.shipping_fee

    if params[:order][:select_address] == "0"
      @order.post_code=current_customer.post_code
      @order.address=current_customer.address
      @order.name=current_customer.full_name

    elsif params[:order][:select_address] == "1" && params[:order][:shipping_id] != nil
      @shipping=Shipping.find(params[:order][:shipping_id])
      @order.post_code=@shipping.post_code
      @order.address=@shipping.address
      @order.name=@shipping.name
    else
      redirect_to request.referer
    end
  end

  def create
    order=Order.new(order_params)
    order.customer_id=current_customer.id
    if order.save
      current_customer.cart_items.each do |cart_item|
        OrderItem.create(order_id: order.id,item_id: cart_item.item_id,amount: cart_item.amount,add_tax_price: cart_item.item.add_tax_price)
      end
      current_customer.cart_items.destroy_all
      redirect_to orders_complete_path
    else
      redirect_to action: :new
    end
  end

  def complete
  end

  private
  def order_params
    params.require(:order).permit(:payment_method,:post_code,:address,:name,:shipping_fee,:total_price)
  end

end

app/controllers/customer/passwords_controller.rb
# frozen_string_literal: true

class Customer::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customer/registrations_controller.rb
# frozen_string_literal: true

class Customer::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  
  def after_sign_up_path_for(resource)
    customers_mypage_path
  end

end

app/controllers/customer/sessions_controller.rb
# frozen_string_literal: true

class Customer::SessionsController < Devise::SessionsController
  before_action :customer_state, only: [:create]
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  protected

  def customer_state
    @customer = Customer.find_by(email: params[:customer][:email])
    if @customer
      if @customer.valid_password?(params[:customer][:password]) && @customer.is_quited
        redirect_to new_customer_registration_path
      end
    end
  end
end

app/controllers/customer/shippings_controller.rb
class Customer::ShippingsController < ApplicationController
  before_action :authenticate_customer!
  def index
    @shipping=Shipping.new
    @shippings=current_customer.shippings
  end

  def create
    shipping=Shipping.new(shipping_params)
    shipping.customer_id=current_customer.id
    if shipping.save
      redirect_back(fallback_location:root_path)
    else
      redirect_to request.referer
    end
  end

  def destroy
    shipping=Shipping.find(params[:id])
    shipping.destroy
    redirect_back(fallback_location:root_path)
  end

  def edit
    @shipping=Shipping.find(params[:id])
  end

  def update
    @shipping=Shipping.find(params[:id])
    if @shipping.update(shipping_params)
      redirect_to shippings_path
    else
      redirect_to request.referer
    end
  end

  private
  def shipping_params
    params.require(:shipping).permit(:post_code,:address,:name)
  end

end

app/controllers/customer/unlocks_controller.rb
# frozen_string_literal: true

class Customer::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/customer/cart_items_helper.rb
module Customer::CartItemsHelper
end

app/helpers/customer/customers_helper.rb
module Customer::CustomersHelper
end

app/views/customer/orders/complete.html.erb
<ol class="nav">
	<li class="nav-form">入力</li>
	<li class="arrow"><i class="fas fa-arrow-right"></i></li>
	<li class="nav-form">確認</li>
	<li class="arrow"><i class="fas fa-arrow-right"></i></li>
	<li class="nav-form current">完了</li>
</ol>

<h4 class="text-center mt-5">ご注文ありがとうございました！</h4>

app/views/customer/orders/confirm.html.erb
<ol class="nav">
	<li class="nav-form">入力</li>
	<li class="arrow"><i class="fas fa-arrow-right"></i></li>
	<li class="nav-form current">確認</li>
	<li class="arrow"><i class="fas fa-arrow-right"></i></li>
	<li class="nav-form">完了</li>
</ol>

<h3><mark>注文情報確認</mark></h3>
<div class="row mt-5">
  <div class="col-lg-7">
    <table class="table">
      <thead class="table-color">
        <th>商品名</th>
        <th>単価</th>
        <th>数量</th>
        <th>小計</th>
      </thead>
      <% current_customer.cart_items.each do |cart_item| %>
      <tr>
        <td><%= cart_item.item.name %></td>
        <td><%= cart_item.item.add_tax_price.to_s(:delimited) %></td>
        <td><%= cart_item.amount %></td>
        <td><%= cart_item.subtotal.to_s(:delimited) %></td>
      </tr>
      <% end %>
    </table>
  </div>
  <div class="col-lg-4 offset-lg-1">

    <table class="table">
      <tr>
        <td class="table-color">送料</td>
        <td><%= @order.shipping_fee %></td>
      </tr>
      <tr>
        <td class="table-color">商品合計</td>
        <td><%= @total_price_except_fee.to_s(:delimited) %></td>
      </tr>
      <tr>
        <td class="table-color">請求金額</td>
        <td><%= @order.total_price.to_s(:delimited) %></td>
      </tr>
    </table>
  </div>
</div>
<div class="d-flex">
  <h6 class="mr-3 font-weight-bold">支払方法</h6>
  <span class="h6"><%= @order.payment_method_i18n %></span>
</div>
<div class="d-flex mt-5">
  <h6 class="mr-3 font-weight-bold">お届け先</h6>
  <div class="h6">〒<%= @order.post_code %><%= @order.address %><br><%= @order.name %></div>
</div>
<%= form_with model:@order,url:orders_path, local:true do |f| %>
  <%= f.hidden_field:shipping_fee,value:@order.shipping_fee %>
  <%= f.hidden_field:total_price,value:@order.total_price %>
  <%= f.hidden_field:payment_method,value:@order.payment_method %>

  <%= f.hidden_field:post_code,value:@order.post_code %>
  <%= f.hidden_field:address,value:@order.address %>
  <%= f.hidden_field:name,value:@order.name %>
  <%= f.submit "注文を確定する",class:"btn register_button motion my-3" %>
<% end %>

app/views/customer/orders/index.html.erb
<div class="row">
  <div class="col m-3">
    <h3><mark>注文履歴一覧</mark></h3>
		<table class="table table-bordered mt-5">
		  <tbody>
			<tr class="table-color">
				<td>注文日</td>
				<td>配送先</td>
				<td>注文商品</td>
				<td>支払金額</td>
				<td>ステータス</td>
				<td>注文詳細</td>
			</tr>
			<% @orders.each do |order| %>
				<tr>
					<td><%= order.created_at.strftime('%Y/%m/%d') %></td>
					<td>〒<%= order.post_code %></br>
					  　<%= order.address %></br>
					  　<%= order.name %>
					</td>
					<td>
						<% order.order_items.each do |order_item| %>
							<%= order_item.item.name %></br>
						<% end %>
					</td>
					<td><%= order.total_price.to_s(:delimited) %></td>
					<td><%= order.ordering_status_i18n %></td>
					<td><%= link_to "表示する", order_path(order), class: "btn move_button motion" %></td>
				</tr>
			<% end %>
 	    </tbody>
		</table>
	</div>
</div>

app/views/customer/orders/new.html.erb
<ol class="nav">
	<li class="nav-form current">入力</li>
	<li class="arrow"><i class="fas fa-arrow-right"></i></li>
	<li class="nav-form">確認</li>
	<li class="arrow"><i class="fas fa-arrow-right"></i></li>
	<li class="nav-form">完了</li>
</ol>

<div class="mt-3">
  <h3><mark>注文情報入力</mark></h3>
  <%= form_with model: @order, url: orders_confirm_path, local: true do |f| %>
  <table>
    <tr><td class="font-weight-bold">支払い方法</td></tr>
    <tr>
      <td>
        <%= f.radio_button:payment_method,@credit_card,checked:true %>
        <%= f.label:payment_method,@credit_card_ja %>
      </td>
      <td></td>
    </tr>
    <tr>
      <td>
        <%= f.radio_button:payment_method,@transfer %>
        <%= f.label:payment_method,@transfer_ja %>
      </td>
      <td></td>
    </tr>
    <tr><td class="font-weight-bold">お届け先</td></tr>
    <tr>
      <td>
        <%= f.radio_button:select_address,0,checked:true %>
        <%= f.label:select_address,"ご自身の住所" %>
      </td>
      <td></td>
    </tr>
    <tr>
      <td><%= current_customer.full_address %></td>
      <td></td>
    </tr>
    <tr>
      <td><%= current_customer.full_name %></td>
    </tr>
    <tr>
      <td>
        <%= f.radio_button:select_address,1 %>
        <%= f.label:select_address,"登録済住所から選択" %>
      </td>
    </tr>
    <tr>
      <td  colspan="2">
        <%= f.select:shipping_id,options_from_collection_for_select(Shipping.where(customer_id:current_customer),:id,:full_address),:size=>"50" %>
      </td>
    </tr>
    <tr>
      <td>
        <%= f.radio_button:select_address,2 %>
        <%= f.label:select_address,"新しいお届け先" %>
      </td>
      <td></td>
    </tr>
      <td><%= f.label:"郵便番号（ハイフンなし）" %></td>
      <td><%= f.number_field:post_code,placeholder:"0000000" %></td>
    <tr>
      <td><%= f.label:"住所" %></td>
      <td><%= f.text_field:address,placeholder:"東京都渋谷区代々木神園町0-0",:size=>"60" %></td>
    </tr>
      <td><%= f.label:"宛名" %></td>
      <td><%= f.text_field:name,placeholder:"令和道子" %></td>
    <tr>
      <td><%= f.submit "確認画面へ進む",class:"btn move_button motion my-3" %></td>
      <td></td>
    </tr>
      <% end %>
  </table>
</div>

app/views/customer/orders/show.html.erb
<div class="row">
  <div class="col m-3">
  	<h3><mark>注文履歴詳細</mark></h3>

  <div class="row">
	  <div class="col-7">

					<h4 class="mt-3"><strog>注文情報</strog></h4>
						<table class="table table-bordered">
							<tbody>
								<tr>
									<td class="table-color">注文日</td>
									<td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
								</tr>
								<tr>
									<td class="table-color">配送先</td>
									<td>〒<%= @order.post_code %></br>
											<%= @order.address %></br>
											<%= @order.name %>
									</td>
								</tr>
								<tr>
									<td class="table-color">支払い方法</td>
									<td><%= @order.payment_method_i18n %></td>
								</tr>
								<tr>
									<td class="table-color">ステータス</td>
									<td><%= @order.ordering_status_i18n %></td>
								</tr>
							</tbody>
						</table>
			</div>
			<div class="col-4">
				<h4 class="mt-3"><strog>請求情報</strog></h4>
					<table class="table table-bordered">
						<tbody>
							<tr>
								<td class="table-color">商品合計</td>
								<td><%= (@order.total_price-@order.shipping_fee).to_s(:delimited) %>円</td>
							</tr>
							<tr>
								<td class="table-color">配送料</td>
								<td><%= @order.shipping_fee %>円</td>
							</tr>
							<tr>
								<th class="table-color">ご請求額</th>
								<td><%= @order.total_price.to_s(:delimited) %>円</td>
							</tr>
						</tbody>
					</table>
				</div>
		</div>

	<div class="row">
		<div class="col-11">
			<h4 class="mt-3"></strog>注文内容</strog></h4>
			　<table class="table table-bordered">
			　	<tbody>
				　	<tr class="table-color">
				　		<td>商品</td>
				　		<td>単価（税込）</td>
				　		<td>個数</td>
				　		<td>小計</td>
				　	</tr>
		
					　<% @order.order_items.each do |order_item| %>
					　	<tr>
					　		<td><%= order_item.item.name %></td>
					　		<td><%= order_item.add_tax_price.to_s(:delimited) %>円</td>
					　		<td><%= order_item.amount %>個</td>
					　		<td><%= order_item.sum_of_item_price.to_s(:delimited) %>円</td>
					　	</tr>
					　<% end %>
					</tbody>
			　</table>
			</div>
	　</div>
	</div>
</div>