config/routes.rb
Rails.application.routes.draw do
  devise_for :admin,skip:[:regstrations,:passwords],controllers:{
    sessions:"admin/sessions"
  }
  namespace :admin do
    root to:"homes#top"
    resources:customers,except:[:new,:create,:destroy]
    resources:items,exept:[:destroy]
    resources:genres,except:[:new,:show,:destroy]
    resources:orders,only:[:show,:update]
    resources:order_items,only:[:update]
  end

  devise_for :customers,skip:[:passwords],controllers:{
    registrations:"customer/registrations",
    sessions:"customer/sessions"
  }

  scope module: :customer do
    root to: "homes#top"
    get "/about" => "homes#about"
    resources:items,only:[:index,:show]
    resources:cart_items,only:[:index,:create,:update,:destroy]
    delete "/cart_items/" => "cart_items#destroy_all",as:"destroy_all"
    post "/orders/confirm" => "orders#confirm"
    get "/orders/complete" => "orders#complete"
    resources:orders,only:[:new,:create,:index,:show]
    resource:customers,only:[:show,:edit,:update]
    get "/customers/mypage" => "customers#show"
    get "/customers/mypage/edit" => "customers#edit"
    patch "/customers/mypage/update" => "customers#update"
    get "/customers/unsubscribe" => "customers#unsubscribe"
    patch "/customers/withdraw" => "customers#withdraw"
    resources:shippings,except:[:new,:show]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to:customer
  belongs_to:item
  
  def subtotal
      item.add_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many:orders,dependent: :destroy
  has_many:cart_items,dependent: :destroy
  has_many:shippings,dependent: :destroy
  
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :email, presence: true
  validates :post_code, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  validates :encrypted_password, presence: true

  def full_address
    '〒' + post_code + ' ' + address + ' '
  end
  def full_name
    last_name + first_name
  end
  def full_name
    self.last_name + self.first_name
  end
  def full_name_kana
    self.last_name_kana + self.first_name_kana
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many:items,dependent: :destroy

  validates :name, presence: true

end

app/models/item.rb
class Item < ApplicationRecord
  attachment:image
  
  has_many:cart_items,dependent: :destroy
  has_many:order_items,dependent: :destroy
  belongs_to:genre
  
  validates :genre_id, presence: true
  validates :name, presence: true
  validates :description, presence: true
  validates :price, presence: true
  validates :image, presence: true
  
  def add_tax_price
      (self.price * 1.1).round
  end

end

app/models/order.rb
class Order < ApplicationRecord
  has_many:order_items,dependent: :destroy
  belongs_to:customer
  
  validates :post_code, presence: true
  validates :address, presence: true
  validates :name, presence: true

  enum payment_method:{credit_card:0,transfer:1}
  enum ordering_status:{payment_waiting:0,confirmation:1,production:2,ready_to_ship:3,shipping_finish:4}

  def sum_of_order_price
    total_price+shipping_fee
  end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to:order
  belongs_to:item

  enum making_status:{impossible:0,production_waiting:1,producing:2,production_finish:3}
  
  def sum_of_item_price
    add_tax_price*amount
  end
end

app/models/shipping.rb
class Shipping < ApplicationRecord
  belongs_to:customer

  validates :post_code, presence: true
  validates :address, presence: true
  validates :name, presence: true

  def full_address
    '〒' + post_code + ' ' + address + ' ' + name
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
    @orders = Order.page(params[:page]).per(10).order(created_at: :desc)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!
  def show
    @order = Order.find(params[:id])
    @order_items = @order.order_items
    @total_price_except_fee = @order_items.inject(0) { |sum, item| sum + item.sum_of_item_price }
    @order.total_price = @total_price_except_fee + @order.shipping_fee
  end
  
  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    if @order.confirmation?
      @order.order_items.each do |order_item|
      order_item.production_waiting!
      end
    end
    redirect_to admin_order_path(@order)
  end

  private

  def order_params
    params.require(:order).permit(:ordering_status)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name,:first_name,:last_name_kana,:first_name_kana,:post_code,:address,:phone_number])
  end
end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < ApplicationController
  before_action :authenticate_customer!
  def new
    @order=Order.new
    @credit_card=Order.payment_methods.key(0)
    @transfer=Order.payment_methods.key(1)
    @credit_card_ja=Order.payment_methods_i18n[:credit_card]
    @transfer_ja=Order.payment_methods_i18n[:transfer]
  end

  def index
    @orders=current_customer.orders
  end

  def show
    if params[:id]=="confirm"
      redirect_to new_order_path
    else
      @order = Order.find(params[:id])
    end
  end

  def confirm
    @order=Order.new(order_params)
    @order.shipping_fee=800
    @total_price_except_fee = current_customer.cart_items.inject(0) { |sum, item| sum + item.subtotal }
    @order.total_price=@total_price_except_fee + @order.shipping_fee

    if params[:order][:select_address] == "0"
      @order.post_code=current_customer.post_code
      @order.address=current_customer.address
      @order.name=current_customer.full_name

    elsif params[:order][:select_address] == "1" && params[:order][:shipping_id] != nil
      @shipping=Shipping.find(params[:order][:shipping_id])
      @order.post_code=@shipping.post_code
      @order.address=@shipping.address
      @order.name=@shipping.name
    else
      redirect_to request.referer
    end
  end

  def create
    order=Order.new(order_params)
    order.customer_id=current_customer.id
    if order.save
      current_customer.cart_items.each do |cart_item|
        OrderItem.create(order_id: order.id,item_id: cart_item.item_id,amount: cart_item.amount,add_tax_price: cart_item.item.add_tax_price)
      end
      current_customer.cart_items.destroy_all
      redirect_to orders_complete_path
    else
      redirect_to action: :new
    end
  end

  def complete
  end

  private
  def order_params
    params.require(:order).permit(:payment_method,:post_code,:address,:name,:shipping_fee,:total_price)
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_items_helper.rb
module Admin::OrderItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customer/customers_helper.rb
module Customer::CustomersHelper
end

app/helpers/customer/homes_helper.rb
module Customer::HomesHelper
end

app/helpers/customer/items_helper.rb
module Customer::ItemsHelper
end

app/helpers/customer/orders_helper.rb
module Customer::OrdersHelper
end

app/helpers/customer/shippings_helper.rb
module Customer::ShippingsHelper
end

app/views/admin/orders/show.html.erb
<div class="row">
  <div class="col m-3">
    <h3><mark>注文履歴詳細</mark></h3>
    <div class="row">
      <div class="col-md-8">
        <table class="table table-borderless">
          <tr>
            <th>購入者</th>
            <td>
              <%= link_to admin_customer_path(@order.customer.id), class: "link" do %>
              <%= @order.customer.last_name %><%= @order.customer.first_name %>
              <% end %>
            </td>
          </tr>
          <tr>
            <th>注文日</th>
            <td><%= @order.created_at.strftime("%Y/%m/%d") %></td>
          </tr>
          <tr>
            <th>配送先</th>
            <td>〒<%= @order.post_code %><%= @order.address %><br><%= @order.name %></td>
          </tr>
          <tr>
            <th>支払方法</th>
            <td><%= @order.payment_method_i18n %></td>
          </tr>
          <tr>
            <th>注文ステータス</th>
            <td>
              <%= form_with url: admin_order_path(@order), model:@order, method: :patch, local:true do |f| %>
                <%= f.select :ordering_status, Order.ordering_statuses_i18n.invert, {}, {class: "mr-5",required: true} %>
                <%= f.submit "更新", class: "btn register_button motion" %>
              <% end %>
            </td>
          </tr>
        </table>
      </div>
    </div>
    <div class="row">
      <div class="col-md-8">
        <table class="table table-hover table-inverse">
          <thead class="table-color">
            <tr>
              <th>商品名</th>
              <th>単価(税込)</th>
              <th>数量</th>
              <th>小計</th>
              <th>制作ステータス</th>
            </tr>
          </thead>
          <tbody>
            <% @order_items.each do |order_item| %>
              <tr>
                <td><%= order_item.item.name %></td>
                <td><%= order_item.item.add_tax_price.to_s(:delimited) %></td>
                <td><%= order_item.amount %></td>
                <td><%= order_item.sum_of_item_price.to_s(:delimited) %></td>
                <td>
                  <%= form_with url: admin_order_item_path(order_item), model:order_item, method: :patch, local:true do |s| %>
                    <%= s.select :making_status, OrderItem.making_statuses_i18n.invert, {}, {class: "mr-5",required: true} %>
                    <%= s.submit "更新", class: "btn register_button motion" %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class="offset-md-1">
        <table class="table table-borderless">
          <tr>
            <th class="table-color">商品合計</th>
            <td><%= @total_price_except_fee.to_s(:delimited) %>円</td>
          </tr>
          <tr>
            <th class="table-color">送料</th>
            <td><%= @order.shipping_fee.to_s(:delimited) %>円</td>
          </tr>
          <tr>
            <th class="table-color">請求金額合計</th>
            <td><%= @order.total_price.to_s(:delimited) %>円</td>
          </tr>
        </table>
      </div>
    </div>
  </div>
</div>